title: Aryan Ghadge
author:
  name: Aryan Ghadge
  email: aryanghadge811@gmail.com
description: Personal Profile
logo: /assets/logo.png
permalink: /:title/
lang: "en"
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

#Layout
show_social: true
show_sidebar: false
show_excerpts: false

#Menu

navigation:
- {title: "Home", url: "https://aryanghadge.github.io/"}
- {file: "aryan.pdf", title: "Resume"}
